version: '3'

services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:443"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kochampwr123
      MYSQL_DATABASE: baza
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=kochampwr123


volumes:
  db:
